name: The Film Dream Creatives
analytics: {}
github: true
description: Consulting Agency
author:
  name: The Film Dream Creatives
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/437d7737-107b-47f2-9a66-6dad8c47d6a3.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/437d7737-107b-47f2-9a66-6dad8c47d6a3.png
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.18375327438116074
color:
  lightness: 0.8724299382884055
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  saturation: 0.7834092606790364
  brandStrength: 0.10182219883427024
  rhythmicContrast: 0.9688708949834108
content_rating:
  adult: false
typography_spectrum: 0.08569695800542831
opengraph: {}
title: 'The Film Dream Creatives '
purpose:
  - type: contact
    url: 'mailto:tfdcreatives@thefilmdream.com'
    label: Contact us
